import { useEffect, useState } from 'react';

/**
 * The approval queue — the whole point of the automation.
 *
 * "I don't want to have to remember to do it; I want an automation I can quickly
 * scan and approve." So the draft arrives already written: read it, tweak a line
 * if you like, send. Nothing reaches the client without this step.
 */

interface Summary {
  id: string;
  project_id: string;
  project_name?: string;
  period_start: string;
  period_end: string;
  trigger: 'scheduled' | 'manual' | 'milestone';
  status: 'draft' | 'approved' | 'sent' | 'skipped';
  title: string | null;
  narrative: string | null;
  entry_count: number;
  photo_count: number;
  sent_at: string | null;
  recipients: string | null;
  error: string | null;
  created_at: string;
}

const TRIGGER_LABEL: Record<Summary['trigger'], string> = {
  scheduled: 'On schedule',
  milestone: 'Milestone reached',
  manual: 'Generated by hand',
};

export default function SummaryQueue({ projectId }: { projectId?: string }) {
  const [summaries, setSummaries] = useState<Summary[] | null>(null);
  const [editing, setEditing] = useState<Record<string, { title: string; narrative: string }>>({});
  const [busy, setBusy] = useState<string>('');
  const [message, setMessage] = useState<{ tone: 'ok' | 'bad'; text: string } | null>(null);

  const query = projectId ? `?project_id=${projectId}` : '?status=draft';

  async function load() {
    const res = await fetch(`/api/summaries${query}`);
    if (res.ok) setSummaries(await res.json());
  }
  useEffect(() => { load(); }, [projectId]);

  function draftOf(s: Summary) {
    return editing[s.id] ?? { title: s.title ?? '', narrative: s.narrative ?? '' };
  }

  function edit(s: Summary, field: 'title' | 'narrative', value: string) {
    setEditing((prev) => ({ ...prev, [s.id]: { ...draftOf(s), [field]: value } }));
  }

  async function save(s: Summary) {
    setBusy(s.id);
    try {
      await fetch(`/api/summaries/${s.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(draftOf(s)),
      });
      setMessage({ tone: 'ok', text: 'Draft saved.' });
      await load();
    } finally { setBusy(''); }
  }

  async function send(s: Summary) {
    const edited = draftOf(s);
    if (!confirm(`Send this update to the client?\n\n"${edited.title}"`)) return;

    setBusy(s.id);
    try {
      // Save any edits first, so what gets sent is what's on screen.
      await fetch(`/api/summaries/${s.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(edited),
      });

      const res = await fetch(`/api/summaries/${s.id}`, { method: 'POST' });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to send');

      setMessage({ tone: 'ok', text: `Sent to ${data.recipients.join(', ')}.` });
      await load();
    } catch (err: any) {
      setMessage({ tone: 'bad', text: err.message });
    } finally { setBusy(''); }
  }

  async function dismiss(s: Summary) {
    if (!confirm('Dismiss this update without sending it?')) return;
    setBusy(s.id);
    try {
      await fetch(`/api/summaries/${s.id}`, { method: 'DELETE' });
      await load();
    } finally { setBusy(''); }
  }

  async function generateNow() {
    if (!projectId) return;
    setBusy('new');
    setMessage(null);
    try {
      const res = await fetch('/api/summaries', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ project_id: projectId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed');
      await load();
    } catch (err: any) {
      setMessage({ tone: 'bad', text: err.message });
    } finally { setBusy(''); }
  }

  if (!summaries) return <p className="text-sm text-gray-500">Loading…</p>;

  const drafts = summaries.filter((s) => s.status === 'draft');
  const past = summaries.filter((s) => s.status !== 'draft');

  return (
    <div className="space-y-4">
      {message && (
        <div className={`text-sm rounded-md px-3 py-2 ${
          message.tone === 'ok'
            ? 'bg-green-50 text-green-800 border border-green-200'
            : 'bg-red-50 text-red-700 border border-red-200'
        }`}>
          {message.text}
        </div>
      )}

      {projectId && (
        <button
          type="button"
          onClick={generateNow}
          disabled={busy === 'new'}
          className="text-sm font-semibold px-3 py-2 rounded-md bg-[#AEDE4A] hover:bg-[#9BCF3A] text-gray-900 disabled:opacity-50"
        >
          {busy === 'new' ? 'Writing…' : 'Generate an update now'}
        </button>
      )}

      {drafts.length === 0 && (
        <div className="bg-white rounded-lg border border-gray-200 p-6 text-center text-sm text-gray-500">
          Nothing waiting for approval.
        </div>
      )}

      {drafts.map((s) => {
        const d = draftOf(s);
        return (
          <div key={s.id} className="bg-white rounded-lg border border-gray-200 p-4 space-y-3">
            <div className="flex items-start justify-between gap-3">
              <div className="text-xs text-gray-500">
                <span className="inline-block px-2 py-0.5 rounded-full bg-gray-100 text-gray-700 font-medium mr-2">
                  {TRIGGER_LABEL[s.trigger]}
                </span>
                {s.project_name && <span className="font-medium text-gray-700">{s.project_name} · </span>}
                {s.period_start} to {s.period_end} · {s.entry_count} day{s.entry_count === 1 ? '' : 's'}
                {s.photo_count > 0 && ` · ${s.photo_count} photo${s.photo_count === 1 ? '' : 's'}`}
              </div>
            </div>

            {s.error && (
              <div className="text-xs bg-amber-50 border border-amber-200 text-amber-800 rounded-md px-2 py-1.5">
                {s.error} — write the update below by hand before sending.
              </div>
            )}

            <input
              type="text"
              value={d.title}
              onChange={(e) => edit(s, 'title', e.target.value)}
              placeholder="Subject line"
              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm font-semibold text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#AEDE4A]"
            />
            <textarea
              value={d.narrative}
              onChange={(e) => edit(s, 'narrative', e.target.value)}
              rows={8}
              placeholder="The update the client will read…"
              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#AEDE4A] resize-y"
            />

            <p className="text-xs text-gray-400">
              Drafted from the site diary. Read it before sending — it goes straight to the client.
            </p>

            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => send(s)}
                disabled={busy === s.id || !d.narrative.trim()}
                className="px-4 py-2 rounded-md bg-[#83B81A] hover:bg-[#6f9e16] text-white text-sm font-semibold disabled:opacity-50"
              >
                {busy === s.id ? 'Sending…' : 'Approve & send'}
              </button>
              <button
                type="button"
                onClick={() => save(s)}
                disabled={busy === s.id}
                className="px-3 py-2 rounded-md bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm font-medium disabled:opacity-50"
              >
                Save draft
              </button>
              <button
                type="button"
                onClick={() => dismiss(s)}
                disabled={busy === s.id}
                className="px-3 py-2 text-sm text-gray-500 hover:text-red-600 disabled:opacity-50"
              >
                Dismiss
              </button>
            </div>
          </div>
        );
      })}

      {past.length > 0 && (
        <div className="pt-2">
          <h3 className="text-xs font-semibold uppercase tracking-wide text-gray-400 mb-2">Sent</h3>
          <div className="space-y-1">
            {past.map((s) => (
              <div key={s.id} className="bg-white rounded-md border border-gray-200 px-3 py-2 flex items-center justify-between gap-3">
                <div className="min-w-0">
                  <div className="text-sm font-medium text-gray-900 truncate">
                    {s.title || `${s.period_start} – ${s.period_end}`}
                  </div>
                  <div className="text-xs text-gray-400">
                    {s.status === 'sent'
                      ? `Sent ${s.sent_at?.split(' ')[0]}${s.recipients ? ` to ${s.recipients}` : ''}`
                      : 'Dismissed'}
                  </div>
                </div>
                <span className={`text-xs px-2 py-0.5 rounded-full flex-shrink-0 ${
                  s.status === 'sent' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-500'
                }`}>
                  {s.status}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
